version: "3"
services:
  fs-mysql:
    image: mysql:8
    networks:
      - gateway
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nokia

  file-service:
    build: ./file-service
    ports:
      - "8081:8081"
    networks:
      - gateway
    depends_on:
      - fs-mysql